### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by kavkaz** [kavkaz/pavo#9]
- [ ] Middleware for set cookie `pavo`
- [ ] Handlers
- [ ] Serializers
- [ ] Controllers
- [ ] Params
- [ ] #8 Format slug of version
- [ ] #7 Set thumbnail sizes from CLI options
- [ ] #6 Replace version
- [ ] #4 Header Range
- [ ] HTTP API docs
